### ISSUE TITLE
Implement "Empty Component" thingy

### ISSUE THREAD

**Issue by cburgdorf** [thoughtram/clog#2]
https://github.com/ajoslin/conventional-changelog/blob/master/lib/writer.js#L82

**Comment by vyp** [comment]
Dead link. (Because writer.js renamed to Writer.js I presume.) I think you meant https://github.com/ajoslin/conventional-changelog/blob/37f5561553c30d8f0f2c949502ea278da64949cd/lib/writer.js#L82.

(Also, for the current the current: https://github.com/ajoslin/conventional-changelog/blob/be0808e70890abc344fa3250b35d6014fe75aa92/lib/Writer.js#L144.)

**Comment by kbknapp** [comment]
I'm not a JS guy...so what does this actually do? Is it simply allowing you do a `feat(): some message`? If so, I may be able to try this out later this week.

**Comment by cburgdorf** [comment]
Exactly, and I think it's also allowed to shortcut that to `feat: some message`

**Comment by kbknapp** [comment]
:+1

**Comment by orclev** [comment]
This would be a nice feature to have.
