### ISSUE TITLE
Provide Arch AUR package

### ISSUE THREAD

**Issue by kbknapp** [thoughtram/clog#24]
@vyp 

To alleviate some of the discussion from #20 I've started this issue.

I've uploaded a `rust-beta-bin` package to the AUR which you can use in your makedepends array since we're targeting stable Rust (even though `clog` should *also* build just fine with nightly). This provides `cargo` and `rust` so you won't need to specify those as a make-dep any more.

**Comment by vyp** [comment]
Wow, awesome! I just installed it and it works. So thanks so much, because I'll be using this until the stable release. :)

And I updated clog-git. I think this issue can serve as discussion place for the AUR package if the need arises. But I have no problems with closing it if you want to, because it's not really an 'issue' (we still get notifications for messages on closed issues right?).

**Comment by kbknapp** [comment]
Yep we'll still get notified even if its closed :) and we can always reopen it if needed.
