### ISSUE TITLE
chore: add more default sections

### ISSUE THREAD

**Issue by kbknapp** [thoughtram/clog#62]
Currently we ship with only `Bug Fixes` and `Features` the [angular conventions](https://github.com/ajoslin/conventional-changelog/blob/38e3faa7dcff12bb057b781745b7253cf1bd8be2/conventions/angular.md) we link to uses quite a few more sections as well. It'd be nice to ship with a few more of the default sections, perhaps not all of them, but at least a few that are nice to display in a changelog (such as performance, test, docs, etc.)

**Comment by PascalPrecht** [comment]
@kbknapp yes please! :+1:

**Comment by cburgdorf** [comment]
Absolutely. I wasn't even aware that we haven't enabled such as default section. I think it would be nice to support all of the default sections that the Angular conventions support. But isn't it that things that are `chore` shouldn't end up in the changelog according to the Angular conventions?

**Comment by vyp** [comment]
I mentioned this link in another comment, but just for clarity, we should also keep tabs on https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#-git-commit-guidelines, because they update it often, and it's from the angular repo itself. For example, they seem to have added a "revert" section.

---

On topic, which ones exactly? I agree with @cburgdorf that chore probably should not be in the changelog (at least by default). And I think we can definitely keep out style and refactor right? If so, that leaves us with docs, perf, and test.

My vote is for docs. For example, seeing the changes to documentation in the changelog allows users to know that there's some new reading material (or what instructions have become obsolete if documentation was removed) without needing to go through the commit messages. Not so sure about test and perf though. Thoughts?

**Comment by kbknapp** [comment]
@cburgdorf  @vyp I think only ones *most* end-user would care about (which may be slightly different for a library vs a binary), and leave off chore/style/refactor (since user can Opt-In to those by adding them to a `.clog.toml`).

My vote would be: `perf`, `docs`, `test`, `fix`, and `feat` for the defaults.

**Comment by vyp** [comment]
> which may be slightly different for a library vs a binary

That's what I was thinking too. For a library for example, `perf` would be really important, but a binary maybe not so much (a perf improvement is great, but most users would take that as granted that perf improvements are made whenever possible for a binary). But we have no way of detecting if it's a library or if it's a normal application, unless we add an option, but I think that would be overdoing it way too much.

I think for the sake of this issue maybe we should just assume it's a binary application, as that's probably more common?

And `test`, I consider it more of a *development* thing. Which is to say that most users probably won't care about that section, because it's just the developers making sure their application works.

Just my opinions of course, let me know what you guys think.

**Comment by cburgdorf** [comment]
To be honest I think perf is very important even for end users looking at
the changelog of their favourite application. They may be even longing for
a specific perf improvement.

And then, it's easy enough to overwrite our default sections to remove perf
if someone really doesn't want to have it included.
Am 16.07.2015 10:16 schrieb "RWS" <notifications@github.com>:

**Comment by vyp** [comment]
@cburgdorf Okay no worries. What's your view on having `test` by default?

**Comment by cburgdorf** [comment]
Probably not as it doesn't really belong to the shipped code. But I'm very
much open to other opinions.
Am 16.07.2015 18:03 schrieb "vyp" <notifications@github.com>:

**Comment by vyp** [comment]
@cburgdorf Agreed. @kbknapp voted for `test` above though.

@kbknapp How would you feel to compromise on `perf`, `docs`, `fix` and `feat`? Unless of course you think `test` still has a case to be a default.

**Comment by cburgdorf** [comment]
So I'm voting for `perf`, `fix`, and `feat` for the defaults. Because in my eyes `docs` and `tests` (while extremely important) don't really contribute to the actual code. For me the changelog is a about changes *in* the software.

Again, it's easy enough to to overwrite the sections so I'm happy to go with different defaults if you have different opinions about it.

@PascalPrecht ?

**Comment by kbknapp** [comment]
I'm good with leaving out `test` and `docs`, it's super simple to add them in manually if that's what the user wants :)

**Comment by vyp** [comment]
:+1:
